version: '3.8'

services:
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"  # Внешний порт другой!
    environment:
      - DB_HOST=postgres_db2
      - DB_USER=${DB_USER2}
      - DB_PASS=${DB_PASS2}
      - DB_NAME=${DB_NAME2}
      - DB_PORT=5433
    depends_on:
      - postgres_db2
    volumes:
      - .:/app
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    container_name: app2

  postgres_db2:
    image: postgres:alpine
    environment:
      - SSL_MODE=disable
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - TZ=GMT-3
    ports:
      - "5445:5432"  # Внешний порт другой!
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: postgres_db2

volumes:
  postgres_data_2:
