version: '3.8'

services:
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    ports:
      - "8001:8000"  # Внешний порт для второго проекта
    environment:
      - DB_HOST=postgres_db2
      - DB_PORT=5432  # Внутренний порт PostgreSQL (не менять!)
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
    depends_on:
      - postgres_db2
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  postgres_db2:
    image: postgres:alpine
    container_name: postgres_db2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - TZ=GMT-3
    ports:
      - "5445:5432"  # Порт для подключения с хоста (например, PgAdmin)
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_2:
